export const DomainEvents = {
  APPLICATION_SUBMITTED: 'application.submitted',
  APPLICATION_SCORED: 'application.scored',
  APPLICATION_DENIED: 'application.denied',
  APPLICATION_APPROVED: 'application.approved',
  WAITLIST_ENTERED: 'waitlist.entered',
  LEASE_DRAFT_REQUESTED: 'lease.draft.requested',
  SIGNATURE_PACKET_SENT: 'signature.packet.sent',
  MOVE_IN_SCHEDULED: 'move_in.scheduled',
  INSPECTION_SUBMITTED: 'inspection.submitted',
  INSPECTION_DISPUTED: 'inspection.disputed',
  MAINTENANCE_REQUEST_SUBMITTED: 'maintenance.request.submitted',
  MAINTENANCE_REQUEST_MARKED_EMERGENCY: 'maintenance.request.marked_emergency',
  MAINTENANCE_COMPLETED: 'maintenance.completed',
  RENT_REMINDER_CHECK: 'rent.reminder.check',
  RENT_PAYMENT_POSTED: 'rent.payment.posted',
  DELINQUENCY_THRESHOLD_REACHED: 'delinquency.threshold.reached',
  LATE_FEE_CHECK: 'late_fee.check',
  PAYMENT_PLAN_ELIGIBILITY_CHECK: 'payment_plan.eligibility.check',
  NOTICE_GENERATION_CHECK: 'notice.generation.check',
  NOTICE_SERVED: 'notice.served',
  ATTORNEY_REFERRAL_CHECK: 'attorney.referral.check',
  COURT_DATE_RECORDED: 'court_date.recorded',
  LEASE_90_DAY_RENEWAL_WINDOW: 'lease.90_day_renewal_window',
  LEASE_30_DAY_RENEWAL_WINDOW: 'lease.30_day_renewal_window',
  MOVE_OUT_INSPECTION_COMPLETED: 'move_out.inspection.completed',
  MONTH_END_CLOSE_REQUESTED: 'month_end.close.requested',
  MONTH_END_REOPEN_REQUESTED: 'month_end.reopen.requested',
  LISTING_PUBLISH_REQUESTED: 'listing.publish.requested',
  UNIT_LEASED: 'unit.leased',
} as const;

export type DomainEventType = (typeof DomainEvents)[keyof typeof DomainEvents];

